version: "3.8"

services:
  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: grafana
  #   ports:
  #     - "3000:3000"

  collector:
    image: otel/opentelemetry-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - 4318:4318
      - 4317:4317
    depends_on:
      - zipkin
      - loki
  
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
  
  loki:
    image: grafana/loki
    ports:
      - 3100:3100