version: "3.8"

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/configs/prometheus.yml
    command:
      - '--config.file=/configs/prometheus.yml'

  collector:
    image: otel/opentelemetry-collector-contrib
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - ./files:/etc/output/
    ports:
      - 4318:4318
      - 4317:4317
      - 8888:8888
      - 8889:8889
    depends_on:
      - zipkin
      - loki
      - prometheus
  
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
  
  loki:
    image: grafana/loki
    ports:
      - 3100:3100