version: "3.8"

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - open-telemetry
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/configs/prometheus.yml
    command:
      - '--config.file=/configs/prometheus.yml'
    networks:
      - open-telemetry

  collector:
    image: otel/opentelemetry-collector-contrib
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - ./files:/etc/output/
    ports:
      - 4318:4318
      - 4317:4317
      - 8888:8888
      - 8889:8889
    networks:
      - open-telemetry
    depends_on:
      - elastic
  
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    networks:
      - open-telemetry
  
  loki:
    image: grafana/loki
    ports:
      - 3100:3100
    networks:
      - open-telemetry
  
  
  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo-local.yaml:/etc/tempo.yaml
      - ./tempo-data:/tmp/tempo
    ports:
      - "3200:3200"   # tempo
      - "4321:4317"  # otlp grpc
      - "4322:4318"  # otlp http

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pwd
    networks:
      - open-telemetry


networks: 
  open-telemetry:
    driver: bridge  