receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:

  prometheus:
    endpoint: "0.0.0.0:8889"

  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"

  # tempo:
  #   endpoint: tempo:4322
  #   insecure: false
  
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    format: json
    labels:
      resource:
        deployment.environment: "deployment_environment"
        host.name: "host_name"
        service.name: "service_name"
        service.namespace: "service_namespace"
      record:
        severity: "severity"
    tenant_id: tenant1
    tls:
      insecure: true

  file:
    path: /etc/output/logs.json
  
  # otlphttp/elasticsearch: 
  #   endpoint: "http://elastic:9200"

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check,pprof,zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [zipkin]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [file, loki]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [file, prometheus]