receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:

  prometheus:
    endpoint: "0.0.0.0:8889"

  # prometheusremotewrite:
  #   endpoint: "http://prometheus:9090/api/v1/write"
  #   tls:
  #     insecure: true

  # zipkin:
  #   endpoint: "http://zipkin:9411/api/v2/spans"

  # tempo:
  #   endpoint: tempo:4322
  #   insecure: false
  
  # loki:
  #   endpoint: http://loki:3100/loki/api/v1/push
  #   format: json
  #   labels:
  #     resource:
  #       deployment.environment: "deployment_environment"
  #       host.name: "host_name"
  #       service.name: "service_name"
  #       service.namespace: "service_namespace"
  #     record:
  #       severity: "severity"
  #   tenant_id: tenant1
  #   tls:
  #     insecure: true

  # file:
  #   path: /etc/output/logs2.json
  
extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check,pprof,zpages]
  pipelines:
    # traces:
    #   receivers: [otlp]
    #   exporters: [otlp/data-prepper]
    # logs:
    #   receivers: [otlp]
    #   exporters: [otlp/data-prepper]
    metrics:
      receivers: [otlp]
      exporters: [prometheus]