# my global config
global:
  scrape_interval:     2s 
  evaluation_interval: 2s 
  external_labels:
      monitor: 'codelab-monitor'

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
- job_name: 'otel-collector'
  scrape_interval: 3s
  static_configs:
  - targets: ['collector:8889']
  - targets: ['collector:8888']